import React, { useRef, useState, useEffect } from "react";
import "./Subaffiliate.css";

function SubAffiliatesPage() {
  const stepsListRef = useRef(null);
  const [index, setIndex] = useState(0);
  const [visibleSteps, setVisibleSteps] = useState(3);

  const steps = [
    {
      title: "Step 1",
      text: "Forex brokers offer an affiliate program to their partners, known as primary affiliates or simply -affiliates.",
    },
    {
      title: "Step 2",
      text: "The primary affiliate recruits other individuals or companies to promote the forex broker’s services, these individuals or companies are known as sub-affiliates.",
    },
    {
      title: "Step 3",
      text: "The sub-affiliates promote the forex broker’s services through their own channels such as websites, social media, or email lists.",
    },
    {
      title: "Step 4",
      text: "When a user signs up through a sub-affiliate, the affiliate earns a commission based on the referral, which is passed on to the primary affiliate.",
    },
  ];

  // Update visible steps on window resize
  useEffect(() => {
    const handleResize = () => {
      if (window.innerWidth < 768) setVisibleSteps(1);
      else if (window.innerWidth < 1024) setVisibleSteps(2);
      else setVisibleSteps(3);
    };
    handleResize();
    window.addEventListener("resize", handleResize);
    return () => window.removeEventListener("resize", handleResize);
  }, []);

  const slideNext = () => {
    setIndex((prev) => (prev + 1 > steps.length - visibleSteps ? 0 : prev + 1));
  };

  const slidePrev = () => {
    setIndex((prev) => (prev - 1 < 0 ? steps.length - visibleSteps : prev - 1));
  };

  useEffect(() => {
    if (!stepsListRef.current) return;
    const stepWidth =
      stepsListRef.current.querySelector(".step").offsetWidth +
      parseInt(getComputedStyle(stepsListRef.current.querySelector(".step")).marginRight);
    stepsListRef.current.style.transform = `translateX(-${index * stepWidth}px)`;
  }, [index, visibleSteps]);

  return (
    <div className="sub-affiliates-page">
      {/* Hero Section */}
      <section className="sub-hero-section">
        <img
          className="hero-bg"
          src="/sub-affiliate-banner.jpg"
          alt="Sub-Affiliates Hero"
        />
        <div className="hero-content">
          <p className="breadcrumb">
            HOME &gt; AFFILIATES &gt; CPA STRUCTURES &gt; <strong>SUB-AFFILIATES</strong>
          </p>
          <h1>Sub-Affiliates</h1>
        </div>
      </section>

      {/* How it works section */}
      <section className="sub-how-it-works">
        <div className="sub-how-container">
          <div className="how-left">
            <h2>How Do Sub-Affiliates Operate?</h2>
          </div>
          <div className="how-right">
            <p>
              Sub-Affiliates operate by recruiting other individuals or companies to promote the
              products and services through our existing affiliate program. The primary affiliate
              receives a commission for the sales generated by their sub-affiliates.
            </p>
          </div>
        </div>
      </section>

      {/* Image Section */}
      <section className="image_section_left">
        <div className="image_section_div_1">
          <div className="image_section_div_1_left">
            <h1 className="image_section_h1">
              The Primary Affiliate And Their Sub-Affiliates Work Together To Promote Our Products And Services.
            </h1>
            <p className="image_sectionh3">
              Primary affiliates receive a commission for the sales generated by their sub-affiliates.
            </p>
            <p className="image_sectionp">
              Sub-affiliates are an important part of how BlackBull increases brand reach and sales, 
              and it’s a great way for affiliates to earn additional commission through the recruitment 
              of sub-affiliates. In the forex industry, sub-affiliates typically promote the services 
              of forex brokers like BlackBull and their trading platforms or the markets they operate in.
            </p>
          </div>
          <div className="image_section_div_1_right">
            <img
              src="/Group-2736.webp"
              alt="Description"
              className="right-image-side"
            />
          </div>
        </div>
      </section>

      {/* Steps Section */}
      <section className="sub-affiliates-steps">
        <div className="steps-container">
          <h2>This Is How Sub-Affiliates Can Help Increase Reach & Visibility</h2>
          <p className="steps-description">
            Sub-affiliates in the forex industry can help increase the reach and visibility of
            forex brokers and generate additional revenue for both the broker and the primary
            affiliate through the recruitment of sub-affiliates.
          </p>

          <div className="steps-wrapper">
            <div className="steps-list" ref={stepsListRef}>
              {steps.map((step, i) => (
                <div
                  key={i}
                  className={`step ${
                    i >= index && i < index + visibleSteps ? "active" : ""
                  }`}
                >
                  <div className="step-number">✔</div>
                  <h3>{step.title}</h3>
                  <p>{step.text}</p>
                </div>
              ))}
            </div>

            {/* Centered slider buttons */}
            <div className="slider-buttons">
              <button
                className="slide-prev"
                onClick={slidePrev}
                aria-label="Previous Step"
              >
                ◀
              </button>
              <button
                className="slide-next"
                onClick={slideNext}
                aria-label="Next Step"
              >
                ▶
              </button>
            </div>
          </div>

          {/* Green Info Section */}
          <div className="green_section-div">
            <div className="sub-affiliate-info">
              <p>
                At BlackBull Partners, the standard rate for sub-affiliates is{" "}
                <span className="highlight-blue">ten per cent</span>. This means that if a
                sub-affiliate earns <span className="highlight-blue">$100</span> for a referral,
                then the primary affiliate will earn <span className="highlight-blue">$10 in addition</span> to this.
                <br />
                Start growing your business today by us and referring sub-affiliates today.
              </p>

              <div className="green-button">Join BlackBull Partners</div>
            </div>
          </div>
        </div>
      </section>
    </div>
  );
}

export default SubAffiliatesPage;
